/**
 * Common envelope every client-submitted event MUST carry. The Cloudflare
 * Worker enriches the envelope server-side (with `seq`, `actor_user_id`,
 * `received_at`, and any rejected/accepted decisions) and writes the
 * authoritative row into `time_*.contractor_event` or `project_event`.
 *
 * Two envelope flavours, one per stream:
 *   - `contractorEventEnvelopeSchema` — keyed by `contractorId`.
 *   - `projectEventEnvelopeSchema`    — keyed by `projectId` + per-aggregate
 *                                        `aggregateKind` + `aggregateId`,
 *                                        which the Worker uses for
 *                                        per-aggregate optimistic concurrency
 *                                        inside the project stream.
 *
 * Pure Zod, no I/O.
 */

import { z } from "zod";

const uuidSchema = z.string().uuid();
const isoTimestampSchema = z
  .string()
  .datetime({ offset: true, message: "expected RFC 3339 timestamp" });

/**
 * Versioning policy: every payload carries an `eventVersion`. Bump per event
 * type when its payload shape changes; old payloads stay readable by tagging
 * the version in the projection / reducer.
 */
export const EVENT_VERSION_V1 = 1 as const;

const baseEventEnvelopeSchema = z.object({
  /**
   * UUID generated by the client for idempotent retries from the offline
   * queue. The Worker treats `(stream, contractorId|projectId, clientEventId)`
   * as a unique key and silently dedupes a re-submitted event by returning
   * the previously-assigned `seq`.
   */
  clientEventId: uuidSchema,

  /**
   * ID of the originating user gesture / job. One UI action that produces
   * several events shares the same `correlationId`; useful for full audit
   * replay and for showing "what did this click change?".
   */
  correlationId: uuidSchema,

  /**
   * The immediate predecessor event that *caused* this one (e.g. a
   * `TaskCompleted` raised in response to a `TaskAssigned` import).
   * Optional — most user-initiated events have no causation.
   */
  causationId: uuidSchema.optional(),

  /**
   * Schema version of the *payload*. Always 1 for now; bump per event type
   * when the payload changes incompatibly. Reducers branch on this.
   */
  eventVersion: z
    .number()
    .int()
    .min(1)
    .default(EVENT_VERSION_V1),

  /**
   * ISO timestamp the client claims the event occurred at. Crucial for
   * offline-queue replays where `received_at` ≠ when-it-actually-happened.
   * The Worker may clamp this to a sane window (no future timestamps, no
   * timestamps before period locks).
   */
  occurredAt: isoTimestampSchema,
});

/**
 * Contractor stream — one stream per contractor, holding their own time
 * entries and approval-flow events. Optimistic concurrency is per-stream
 * (only one writer per contractor at a time, which matches reality: a single
 * person on a single laptop).
 */
export const contractorEventEnvelopeSchema = baseEventEnvelopeSchema.extend({
  contractorId: z
    .number()
    .int()
    .positive("contractorId must be a positive integer"),

  /**
   * Optional optimistic-concurrency token. Server fails the write with a
   * `ConcurrencyConflict` if the current head moved past this value. Omit
   * to opt out (the Worker may still fence with a coarser policy such as
   * "no concurrent timers").
   */
  expectedStreamVersion: z.number().int().nonnegative().optional(),
});

export type ContractorEventEnvelope = z.infer<
  typeof contractorEventEnvelopeSchema
>;

/**
 * Project stream — one stream per project, holding tasks, activities, rates
 * and period-lock events. Optimistic concurrency is *per-aggregate-within
 * stream* (editing Task X doesn't conflict with editing Task Y in the same
 * project). The Worker uses `(projectId, aggregateKind, aggregateId)` as the
 * concurrency key, tracked in `project_aggregate_head.version`.
 */
export const projectAggregateKindSchema = z.enum([
  "task",
  "activity",
  "rate",
  "period_lock",
]);

export type ProjectAggregateKind = z.infer<typeof projectAggregateKindSchema>;

export const projectEventEnvelopeSchema = baseEventEnvelopeSchema.extend({
  projectId: z
    .number()
    .int()
    .positive("projectId must be a positive integer"),
  aggregateKind: projectAggregateKindSchema,
  /**
   * UUID of the aggregate inside the stream — taskId, activityId,
   * rateAggregateId or periodLockId. Generated client-side at "create" time.
   */
  aggregateId: uuidSchema,
  /**
   * Optimistic-concurrency token scoped to this aggregate within the project
   * stream. Optional for the very first event of an aggregate (the
   * `*Created` events).
   */
  expectedAggregateVersion: z.number().int().nonnegative().optional(),
});

export type ProjectEventEnvelope = z.infer<typeof projectEventEnvelopeSchema>;

// Re-exported helpers in case downstream callers want to compose their own
// schemas (e.g. tests that need a full event but want to override one field).
export const eventEnvelopeShared = {
  uuidSchema,
  isoTimestampSchema,
};
