-- TMetric Dashboard Cache
-- Stores fetched TMetric data to avoid repeated API calls.
-- Data is keyed by scope (date range, workspaces, clients, contractors).
-- User clicks Refresh to fetch from TMetric; otherwise we serve from cache.

CREATE TABLE "tmetric_dashboard_cache" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "created_by" uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    "period_start" date NOT NULL,
    "period_end" date NOT NULL,
    "scope" jsonb NOT NULL DEFAULT '{}',
    "data" jsonb NOT NULL
);

ALTER TABLE "tmetric_dashboard_cache"
    ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME "tmetric_dashboard_cache_id_seq"
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

ALTER TABLE "tmetric_dashboard_cache"
    ADD CONSTRAINT "tmetric_dashboard_cache_pkey" PRIMARY KEY ("id");

-- Scope JSON shape: { workspaceIds?: number[], clientIds?: number[], contractorIds?: number[], projectIterationIds?: number[] }
-- Empty arrays or missing keys mean "all" for that dimension.

CREATE INDEX "idx_tmetric_dashboard_cache_created_at" ON "tmetric_dashboard_cache" ("created_at" DESC);
CREATE INDEX "idx_tmetric_dashboard_cache_scope" ON "tmetric_dashboard_cache" USING GIN ("scope");
CREATE INDEX "idx_tmetric_dashboard_cache_period" ON "tmetric_dashboard_cache" ("period_start", "period_end");

ALTER TABLE "tmetric_dashboard_cache" ENABLE ROW LEVEL SECURITY;

-- Users can only read/write their own cache entries
CREATE POLICY "read own tmetric dashboard cache" ON "tmetric_dashboard_cache"
    FOR SELECT USING (created_by = auth.uid());

CREATE POLICY "insert own tmetric dashboard cache" ON "tmetric_dashboard_cache"
    FOR INSERT WITH CHECK (created_by = auth.uid());

CREATE POLICY "delete own tmetric dashboard cache" ON "tmetric_dashboard_cache"
    FOR DELETE USING (created_by = auth.uid());

GRANT ALL ON TABLE "tmetric_dashboard_cache" TO "authenticated";
GRANT ALL ON SEQUENCE "tmetric_dashboard_cache_id_seq" TO "authenticated";

COMMENT ON TABLE "tmetric_dashboard_cache" IS 'Cache for TMetric dashboard data. Fetched on Refresh, served from cache otherwise.';
