-- Add generated report source table
-- This migration creates a table to store generated report sources with versioning support

-- 1. Create the generated_report_source table
CREATE TABLE "public"."generated_report_source" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "project_iteration_id" bigint NOT NULL,
    "data" jsonb NOT NULL
);

-- Add primary key and foreign key constraints
ALTER TABLE "public"."generated_report_source" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."generated_report_source_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."generated_report_source" 
ADD CONSTRAINT "generated_report_source_pkey" PRIMARY KEY ("id");

ALTER TABLE "public"."generated_report_source" 
ADD CONSTRAINT "generated_report_source_project_iteration_id_fkey" FOREIGN KEY ("project_iteration_id") REFERENCES "public"."project_iteration"("id") ON DELETE CASCADE;

-- 2. Enable RLS on the table
ALTER TABLE "public"."generated_report_source" ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS policies that delegate to project_iteration RLS
CREATE POLICY "read generated report sources" ON "public"."generated_report_source" 
FOR SELECT USING ((EXISTS ( 
  SELECT 1 
  FROM "public"."project_iteration" "pi"
  WHERE ("generated_report_source"."project_iteration_id" = "pi"."id")
)));

CREATE POLICY "insert generated report sources" ON "public"."generated_report_source" 
FOR INSERT WITH CHECK ((EXISTS ( 
  SELECT 1 
  FROM "public"."project_iteration" "pi"
  WHERE ("generated_report_source"."project_iteration_id" = "pi"."id")
)));

CREATE POLICY "update generated report sources" ON "public"."generated_report_source" 
FOR UPDATE USING ((EXISTS ( 
  SELECT 1 
  FROM "public"."project_iteration" "pi"
  WHERE ("generated_report_source"."project_iteration_id" = "pi"."id")
))) WITH CHECK (true);

CREATE POLICY "delete generated report sources" ON "public"."generated_report_source" 
FOR DELETE USING ((EXISTS ( 
  SELECT 1 
  FROM "public"."project_iteration" "pi"
  WHERE ("generated_report_source"."project_iteration_id" = "pi"."id")
)));

-- 4. Grant permissions on the new table
GRANT ALL ON TABLE "public"."generated_report_source" TO "anon";
GRANT ALL ON TABLE "public"."generated_report_source" TO "authenticated";
GRANT ALL ON TABLE "public"."generated_report_source" TO "service_role";

GRANT ALL ON SEQUENCE "public"."generated_report_source_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."generated_report_source_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."generated_report_source_id_seq" TO "service_role";

-- 5. Create indexes for performance
CREATE INDEX "idx_generated_report_source_project_iteration_id" ON "public"."generated_report_source" ("project_iteration_id");
CREATE INDEX "idx_generated_report_source_created_at" ON "public"."generated_report_source" ("created_at");
CREATE INDEX "idx_generated_report_source_data_gin" ON "public"."generated_report_source" USING GIN ("data");

-- 6. Add comments
COMMENT ON TABLE "public"."generated_report_source" IS 'Stores generated report sources with versioning support';
COMMENT ON COLUMN "public"."generated_report_source"."project_iteration_id" IS 'Reference to the project iteration this report source belongs to';
COMMENT ON COLUMN "public"."generated_report_source"."created_at" IS 'Timestamp for versioning - when this report source was generated';
COMMENT ON COLUMN "public"."generated_report_source"."data" IS 'JSON data containing the generated report source information';
