-- Budget target is stored only in this log table (no column on project_iteration).
-- Current target = latest row per iteration where new_target_amount IS NOT NULL.
-- Rows with null new_target_amount are billing-only snapshots (e.g. from TMetric refresh) for burndown.
CREATE TABLE IF NOT EXISTS "project_iteration_budget_target_log" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "project_iteration_id" bigint NOT NULL,
  "new_target_amount" double precision NULL,
  "billing_snapshot_amount" double precision NULL,
  "billing_snapshot_currency" text NULL,
  "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "project_iteration_budget_target_log_project_iteration_id_fkey"
    FOREIGN KEY ("project_iteration_id") REFERENCES "project_iteration"("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "idx_project_iteration_budget_target_log_iteration_id"
  ON "project_iteration_budget_target_log" ("project_iteration_id");
CREATE INDEX IF NOT EXISTS "idx_project_iteration_budget_target_log_created_at"
  ON "project_iteration_budget_target_log" ("created_at");

COMMENT ON TABLE "project_iteration_budget_target_log" IS 'Change log for iteration budget target; used to graph billing vs target over time. Billing-only rows (new_target_amount NULL) from e.g. TMetric refresh support burndown.';

ALTER TABLE "project_iteration_budget_target_log" ENABLE ROW LEVEL SECURITY;

-- Allow read or insert if you can see the iteration (project_iteration RLS defines visibility).
CREATE POLICY "read if can see iteration" ON "project_iteration_budget_target_log"
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM "project_iteration" "pi" WHERE "pi"."id" = "project_iteration_budget_target_log"."project_iteration_id")
  );

CREATE POLICY "insert if can see iteration" ON "project_iteration_budget_target_log"
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM "project_iteration" "pi" WHERE "pi"."id" = "project_iteration_budget_target_log"."project_iteration_id")
  );

-- Allow update on budget target log if user can see the iteration.
CREATE POLICY "update if can see iteration" ON "project_iteration_budget_target_log"
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM "project_iteration" "pi" WHERE "pi"."id" = "project_iteration_budget_target_log"."project_iteration_id")
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM "project_iteration" "pi" WHERE "pi"."id" = "project_iteration_budget_target_log"."project_iteration_id")
  );

-- Allow delete on budget target log if user can see the iteration.
CREATE POLICY "delete if can see iteration" ON "project_iteration_budget_target_log"
  FOR DELETE USING (
    EXISTS (SELECT 1 FROM "project_iteration" "pi" WHERE "pi"."id" = "project_iteration_budget_target_log"."project_iteration_id")
  );

GRANT ALL ON TABLE "project_iteration_budget_target_log" TO "authenticated";
GRANT ALL ON TABLE "project_iteration_budget_target_log" TO "service_role";
GRANT USAGE, SELECT ON SEQUENCE "project_iteration_budget_target_log_id_seq" TO "authenticated";
GRANT USAGE, SELECT ON SEQUENCE "project_iteration_budget_target_log_id_seq" TO "service_role";
